project_name: "ViT_ImageNet10"

data: 
 train_root: "data/imagenet-10-split/train"
 val_root: "data/imagenet-10-split/test"
 batch_size: 128   # 根据你的显存调整，ViT 比较吃显存
 num_workers: 8 

model: 
 num_classes: 10
 img_size: 224
 patch_size: 16
 embed_dim: 768
 depth: 12
 num_heads: 12
 mlp_ratio: 4.0 
 drop_rate: 0.1 
 attn_drop_rate: 0.1

train: 
 max_epoch: 50
 lr: 0.001
 weight_decay: 0.05 
 device: "cuda"
 log_dir: "runs/ViT_ImageNet10_4090"
 save_dir: "checkpoint"